/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.jbuttoncolores;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author a20eduardobn
 */
public class ButtonColoresPanel extends javax.swing.JPanel {

    private Color txtColor;
    private Color bgColor;

    /**
     * Creates new form ButtonColoresPanel
     */
    public ButtonColoresPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTextColor = new javax.swing.JLabel();
        lblBgColor = new javax.swing.JLabel();
        txtTextColor = new javax.swing.JTextField();
        txtBgColor = new javax.swing.JTextField();
        btnTextColor = new javax.swing.JButton();
        btnBgColor = new javax.swing.JButton();

        lblTextColor.setText("Cor texto:");

        lblBgColor.setText("Cor fondo:");

        txtTextColor.setEditable(false);

        txtBgColor.setEditable(false);
        txtBgColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBgColorActionPerformed(evt);
            }
        });

        btnTextColor.setText("...");
        btnTextColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTextColorActionPerformed(evt);
            }
        });

        btnBgColor.setText("...");
        btnBgColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBgColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBgColor)
                    .addComponent(lblTextColor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTextColor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBgColor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTextColor)
                    .addComponent(btnBgColor))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTextColor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTextColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTextColor)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBgColor)
                    .addComponent(txtBgColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBgColor))
                .addContainerGap(215, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBgColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBgColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBgColorActionPerformed
    
    private void btnTextColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTextColorActionPerformed
        txtColor = JColorChooser.showDialog(this, "Choose color", Color.yellow);
        txtTextColor.setText(txtColor.getRed() + " " + txtColor.getGreen() + " " + txtColor.getBlue());
    }//GEN-LAST:event_btnTextColorActionPerformed

    private void btnBgColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBgColorActionPerformed
        bgColor = JColorChooser.showDialog(this, "Choose color", Color.yellow);
        txtBgColor.setText(bgColor.getRed() + " " + bgColor.getGreen() + " " + bgColor.getBlue());
    }//GEN-LAST:event_btnBgColorActionPerformed

    public Colores getSelectedValue() {
        if (txtTextColor.getText().isEmpty()){
            return new Colores();
        }
        return new Colores(bgColor, txtColor);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBgColor;
    private javax.swing.JButton btnTextColor;
    private javax.swing.JLabel lblBgColor;
    private javax.swing.JLabel lblTextColor;
    private javax.swing.JTextField txtBgColor;
    private javax.swing.JTextField txtTextColor;
    // End of variables declaration//GEN-END:variables
}
